apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkusasdf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkusasdf
    app.kubernetes.io/part-of: asdf
  name: java-quarkusasdf
  namespace: kkanova
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-quarkusasdf
    weight: 100
status: {}
