apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: java-quarkusasdf
  namespace: kkanova
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: asdf
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-quarkusasdf
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: java-quarkusasdf-
      labels:
        build.appstudio.openshift.io/application: asdf
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-quarkusasdf
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: kkanova
    spec:
      params:
      - name: git-url
        value: https://github.com/dheerajodha/devfile-sample-code-with-quarkus
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:kkanova-java-quarkusasdf-$(tt.params.git-revision)
      - name: dockerfile
        value: src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:ad4c34b71d468a991450b0091cd96765471ed82d
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: java-quarkusasdf/$(tt.params.git-revision)
    status: {}
status: {}
